language: ruby
rvm:
- 2.3.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "k8UBP5SRhXZRHfcM4H33Swr5AODOHilkvVw4ab526Rcr4BWtrkcqsXB+BKZvrsN42kRjRIZzYJCCKrLXXp5/JOougs3JG4JmHY8BQQwSJnOM2GJL4DjnhIsHO36mnbHNDmsNwnLpm84PoQ5VwJrenFWdxuPqJM3L6DlNuRkz4RRkCoD25LudmYFXZzMV9kJLsGjCIuc29kg94GVRRPveNDfvDyQQSCIpHWVSQKcIWdieZLXsCvxi9jalNodYO2GBu1uEhsrRKLcpr7iwrGn6b7Mmo1Pv6egpGKCG80+tljlUqPBRiz0fUIq+rNlnnB0EAmynEYyUij50UQdzzzHticayNXFFRFlLA9ANZJLXj5rGVEoM717R1INQ2RbL1kxmQ7H8uAsP0ivEZG8RP3XUQe9E9QQZYPp6ZFKJgxbHQ507rGQJjudeSvO9w7AQXCm1J3PSy+lvR6dt/kfoiJ+O/2A42oxeEgeJzYx60CbDHETcP97msUz64Jr9I0L36ToKloUoInysIb7MtZXiJvlL79jJxp1aajp1tGXZFscds8TpjCg06E+28aFadHHDXPMoFZQ2dkLL/q6qp4B7tVaADJUCE3O+qfIhQ2ECxsOS2gNLA19dm+mxebxUo5p7Of0sLE5e9AlFBJ7GbXw7XCOI3Q50+ps/kGAf2Bu2+h9d9J4="

