# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            mtcharte
tagline:          'Artist // Achocalla, Bolivia'
description:      'Website of María Teresa Camacho-Hull, Artist // Achoccalla, Bolivia'
url:              http://mtcharte.net
baseurl:          ''

author:
  name:           'María Teresa Camacho-Hull'
  url:            https://twitter.com/mtcharte

paginate:         1

# Multilingual Setup
#languages: ["en", "es"]
#default_lang: "en"
#exclude_from_localization: ["javascript", "images", "css"]
#parallel_localization: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
- jekyll-gist
- jekyll-paginate
#- jekyll-polyglot

