# Permalinks
permalink:        pretty

# Setup
title:            mtcharte
tagline:          Artist
description:      Website of María Teresa Camacho-Hull // Artist // Achocalla, Bolivia
url:              "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:          "" # the subpath of your site

author:
  name:           María Teresa Camacho-Hull
  url:            https://twitter.com/mtcharte

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Portfolio Collection
collections:
  portfolio:
    output: true


# Build settings
markdown:         kramdown
highlighter:      rouge
#theme:            hyde-theme
gems:
  #- jekyll-feed
  #- jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock