# Permalinks
permalink:        pretty

# Setup
title:            mtcharte
tagline:          María Teresa Camacho-Hull
description:      
    en: Website of María Teresa Camacho-Hull // Artist // Achocalla, Bolivia
    es: Sitio de María Teresa Camacho-Hull // Artista // Achocalla, Bolivia
url:              http://mtcharte.net
baseurl:          "" # the subpath of your site

author:
  name:           María Teresa Camacho-Hull
  url:            https://twitter.com/mtcharte

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Polyglot
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["assets", "images", "downloads"]
parallel_localization: true

# Portfolio Collection
collections:
  portfolio:
    output: true


# Build settings
markdown:         kramdown
highlighter:      rouge
#theme:            hyde-theme
gems:
  #- jekyll-feed
  #- jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-polyglot
exclude:
  - Gemfile
  - Gemfile.lock